basePath: /
definitions:
  models.PC:
    properties:
      added_at:
        example: "2023-01-01T00:00:00.00000Z"
        type: string
      cpu:
        example: i9
        type: string
      data_storage:
        example: ssd 1tb
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Super PC
        type: string
      price:
        example: 79999
        type: integer
      ram:
        example: 32
        type: integer
      videocard:
        example: RTX
        type: string
    type: object
  models.SignIn:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  models.SignUp:
    properties:
      email:
        type: string
      name:
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  transport.IDResponse:
    properties:
      id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: Computer store API
  version: v1.8.0
paths:
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Refresh access and refresh tokens
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: bad request body
        "500":
          description: refresh tokens error
      summary: Refresh Tokens
      tags:
      - auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Sign in user
      parameters:
      - description: sign in info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: bad request body
        "500":
          description: sign in error
      summary: Sign In
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign up new user
      parameters:
      - description: sign up info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: bad request body
        "500":
          description: sign up error
      summary: Sign Up
      tags:
      - auth
  /computers:
    get:
      consumes:
      - application/json
      description: Get all pc from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PC'
            type: array
        "500":
          description: get pcs from database error
      security:
      - BearerAuth: []
      summary: Get Computers
      tags:
      - computers
    put:
      consumes:
      - application/json
      description: Add new pc from request body to database
      parameters:
      - description: computer and its accessories
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.PC'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transport.IDResponse'
        "400":
          description: bad request body
        "500":
          description: add pc to database error
      security:
      - BearerAuth: []
      summary: Add Computer
      tags:
      - computers
  /computers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete pc from database by id
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: pc deleted
        "400":
          description: pc with passed id not found
      security:
      - BearerAuth: []
      summary: Delete Computer
      tags:
      - computers
    get:
      consumes:
      - application/json
      description: Get pc from database by id
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PC'
        "400":
          description: bad id passed
        "404":
          description: pc with passed id not found
      security:
      - BearerAuth: []
      summary: Get Computer
      tags:
      - computers
    post:
      consumes:
      - application/json
      description: Update existing pc in database by id
      parameters:
      - description: Computer ID
        in: path
        name: id
        required: true
        type: integer
      - description: new computer or some new accessories
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.PC'
      produces:
      - application/json
      responses:
        "200":
          description: pc updated
        "400":
          description: pc with passed id not found
      security:
      - BearerAuth: []
      summary: Update Computer
      tags:
      - computers
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
